### ISSUE TITLE
Fix specs

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/katuma_reports#31]
## What

Now specs also fail in local:

```
[pau:~/dev/katuma_reports]$ b rspec spec                                                                                         (master✱)
                                                 
An error occurred while loading ./spec/controllers/reports_controller_spec.rb.
Failure/Error: attr_readonly(*column_names) # Required to block update_attribute and update_column

ActiveRecord::StatementInvalid:                                        
  PG::Error: ERROR:  relation "spree_users" does not exist                   
  LINE 5:              WHERE a.attrelid = '"spree_users"'::regclass
                                          ^
  :             SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                       pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"spree_users"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped                       
               ORDER BY a.attnum                                             
# ./app/models/spree/user.rb:10:in `<class:User>'
# ./app/models/spree/user.rb:2:in `<module:Spree>'
# ./app/models/spree/user.rb:1:in `<top (required)>'
# ./app/models/spree/user_decorator.rb:1:in `<top (required)>'
# ./config/application.rb:71:in `block (2 levels) in <class:Application>'
# ./config/application.rb:70:in `glob'                                  
# ./config/application.rb:70:in `block in <class:Application>'
# ./config/environment.rb:5:in `<top (required)>'                           
# ./spec/rails_helper.rb:4:in `require'                                      
# ./spec/rails_helper.rb:4:in `<top (required)>'
# ./spec/controllers/reports_controller_spec.rb:1:in `require'
# ./spec/controllers/reports_controller_spec.rb:1:in `<top (required)>'
# ------------------                             
# --- Caused by: ---                            
# PG::Error:                                                         
#   ERROR:  relation "spree_users" does not exist
#   LINE 5:              WHERE a.attrelid = '"spree_users"'::regclass
#                                           ^
#   ./app/models/spree/user.rb:10:in `<class:User>'          
```
and few others.

**Comment by sauloperez** [comment]
My bad. They do work it's just that I forgot to do `b rake db:test:prepare` from OFN :trollface:
